site_name: RapidGBM Documentation

repo_url: https://github.com/dhmunk/rapidgbm

theme:
  name: "material"

plugins:
  - mkdocstrings:
      default_handler: python
  - search
  - git-revision-date

nav:
  - RapidGBM Intro: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Tutorials: tutorials.md
  - API-reference: reference.md
  - License: License.md