name: Release
on:
  release:
    types:
      - created

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.3.2']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Publish to Pypi
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          # poetry config repositories.testpypi https://test.pypi.org/legacy/
          # poetry config pypi-token.testpypi $TEST_PYPI_TOKEN
          # poetry publish -r testpypi --build
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
